#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    exclude = ["install.private"]

    test_upgrade_from.1.0~ynh1.name = "Upgrade from 1.0~ynh1"
    test_upgrade_from.1.0~ynh1.args.openclaw_version = "latest"
    test_upgrade_from.1.0~ynh1.args.update_channel = "stable"
    test_upgrade_from.1.0~ynh1.args.auto_update = false