#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================

ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================

ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# UPDATE OPENCLAW.JSON
#=================================================

ynh_script_progression "Updating OpenClaw configuration..."

ynh_app_setting_set --key=domain --value="$new_domain"
ynh_app_setting_set --key=path --value="$new_path"

export OPENCLAW_BIN="$(openclaw_bin)"
export OPENCLAW_STATE_DIR="$(openclaw_state_dir)"

ynh_config_add --template="openclaw.json" --destination="$data_dir/openclaw.json"

#=================================================
# START SYSTEMD SERVICE
#=================================================

ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"